name: create-container-frontend
permissions:
  actions: write
  packages: write
  contents: read

env:
  imageRepository: 'frontend'
  containerRegistry: 'ghcr.io/vriesmarcel'
  dockerfilePath: 'frontend/Dockerfile'
  deploymentFile: 'frontend.yaml'
  namespace: 'globoticket'
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.refname }}
  # If this is enabled it will cancel current running and start latest
  cancel-in-progress: true

jobs:
  build:
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
          context: ${{github.workspace}}
          file: ${{env.dockerfilePath}}
          push: false
          tags: ${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
    
    #scan the containers on known vulnerabilities and break when they are found at level High and Critical    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}}'
        format: 'table'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'
        
    - name: push image to the registry
      run: |
        docker push ${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}}
