name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  container-build-job:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0
      volumes:
        - ${{github.workspace}}:/src
    steps:
      - name: find root folders
        run: ls /
      - name: find src folders
        run: ls /src
      - name: find __w folders
        run: ls /__w
      - name: find working dir folders
        run: ls -R /__w/github-actions-in-action
      - name: find contents of github/home
        run: ls -R /github/home
        
      - name: Build with dotnet
        run: dotnet build ${{github.workspace}}/frontend/frontend.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{github.workspace}}/frontend/frontend.csproj -c Release -o ${{github.workspace}}/app/publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: ${{github.workspace}}/app/publish
