name: "chapter 09: create release frontend"
permissions:
  actions: write
  packages: write
  contents: read

on:
  registry_package: 
     types: [published] 


jobs:
  release:
    uses: ./.github/workflows/create-release.yml
    with:
      deploymentFile: 'frontend.yaml'
      deploymentfileFolder: 'deployment-automation'
    secrets:
      EXTENDED_ACCESSTOKEN: ${{ secrets.EXTENDED_ACCESSTOKEN }}