name: create release frontend
permissions:
  actions: write
  packages: write
  contents: read

env:
  deploymentFile: 'frontend.yaml'

on:
  registry_package: 
     types: [published] 
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.registry_package.package_version.container_metadata.tag.name != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.0
        with:
          files: ${{github.workspace}}/deployment-automation/${{env.deploymentFile}}
        env: 
          Build.version: ${{github.event.registry_package.package_version.container_metadata.tag.name}}

      - name: create a relase with version provided by package push
        uses: softprops/action-gh-release
        with:
          token: "${{ secrets.EXTENDED_ACCESSTOKEN }}"
          tag_name: ${{github.event.registry_package.package_version.container_metadata.tag.name}}
          generate_release_notes: true
          files: |
            ${{github.workspace}}/deployment-automation/${{env.deploymentFile}}

  
