name: "chapter 09: create release"
permissions:
  actions: write
  packages: write
  contents: read
on:
  registry_package: 
    types: [published]

env:
  deploymentfileFolder: 'deployment-automation'
  GH_TOKEN: ${{ github.token }} #required for gh tool

jobs:
  release:
    if: github.event.registry_package.package_version.container_metadata.tag.name != ''
    concurrency:
      group: ${{github.event.registry_package.package_version.container_metadata.tag.name}}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Retrieve latest image version frontend 
        run: |
          export FRONTED_VERSION=$(gh api user/packages/container/frontend/versions | jq -r '.[0].metadata.container.tags[0]') 
          echo "FRONTED_VERSION=$FRONTED_VERSION" >> $GITHUB_ENV
      - name: Retrieve latest image version ordering 
        run: |
          export ORDERING_VERSION=$(gh api user/packages/container/ordering/versions | jq -r '.[0].metadata.container.tags[0]')
          echo "ORDERING_VERSION=$ORDERING_VERSION" >> $GITHUB_ENV
      - name: Retrieve latest image version catalog 
        run: |
          export CATALOG_VERSION=$(gh api user/packages/container/catalog/versions | jq -r '.[0].metadata.container.tags[0]')   
          echo "CATALOG_VERSION=$CATALOG_VERSION" >> $GITHUB_ENV

      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.0
        with:
          files: '["${{github.workspace}}/${{env.deploymentfileFolder}}/catalog.yaml"]'
        env: 
          Build.version: ${{env.CATALOG_VERSION}}

      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.0
        with:
          files: '["${{github.workspace}}/${{env.deploymentfileFolder}}/frontend.yaml"]'
        env: 
          Build.version: ${{env.FRONTED_VERSION}}

      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.0
        with:
          files: '["${{github.workspace}}/${{env.deploymentfileFolder}}/ordering.yaml"]'
        env: 
          Build.version: ${{env.ORDERING_VERSION}}

      - name: create a relase with version provided by package push
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.EXTENDED_ACCESSTOKEN }}"
          tag_name: "v${{github.event.registry_package.package_version.container_metadata.tag.name}}"
          generate_release_notes: true
          files: |
            ${{github.workspace}}/${{env.deploymentfileFolder}}/frontend.yaml
            ${{github.workspace}}/${{env.deploymentfileFolder}}/ordering.yaml
            ${{github.workspace}}/${{env.deploymentfileFolder}}/catalog.yaml
  

