name: "chapter 09: create release"
permissions:
  actions: write
  packages: write
  contents: read
on:
  workflow_call:
    inputs:
      deploymentFile:
        required: true
        type: string
      deploymentfileFolder:
        required: true
        type: string
    secrets:
      EXTENDED_ACCESSTOKEN:
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.0
        with:
          files: ${{github.workspace}}/${{inputs.deploymentfileFolder}}/${{inputs.deploymentFile}}
        env: 
          Build.version: ${{github.event.registry_package.package_version.container_metadata.tag.name}}

      - name: create a relase with version provided by package push
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.EXTENDED_ACCESSTOKEN }}"
          tag_name: "v${{github.event.registry_package.package_version.container_metadata.tag.name}}"
          generate_release_notes: true
          files: |
            ${{github.workspace}}/${{inputs.deploymentfileFolder}}/${{inputs.deploymentFile}}

  

