name: "chapter 09: create-container-and-push-frontend"
permissions:
  actions: write
  packages: write
  contents: read

on:
  push:
    branches: ["main"]
    paths:
    - 'frontend/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/create-container-and-push.yml
    with:
      imageRepository: 'frontend'
      containerRegistry: 'ghcr.io/vriesmarcel'
      dockerfilePath: 'frontend/Dockerfile'
      deploymentFile: 'frontend.yaml'
      namespace: 'globoticket'
    secrets:
      registryPassword: '${{ secrets.EXTENDED_ACCESSTOKEN }}'