name: "chapter 09: create release"
permissions:
  actions: write
  packages: write
  contents: read
on:
  registry_package: 
      types: [published]

env:
  deploymentfileFolder: 'deploymentfiles'

jobs:
  release:
    if: ${{ github.event.registry_package.package_version.container_metadata.tag.name != '' }}
    concurrency:
      group: ${{github.event.registry_package.package_version.container_metadata.tag.name}}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.0
        with:
          files: '["${{github.workspace}}/${{env.deploymentfileFolder}}/frontend.yml","${{github.workspace}}/${{env.deploymentfileFolder}}/ordering.yml","${{github.workspace}}/${{env.deploymentfileFolder}}/catalog.yml"]'
        env: 
          Build.version: ${{github.event.registry_package.package_version.container_metadata.tag.name}}

      - name: create a relase with version provided by package push
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.EXTENDED_ACCESSTOKEN }}"
          tag_name: "v${{github.event.registry_package.package_version.container_metadata.tag.name}}"
          generate_release_notes: true
          files: |
            ${{github.workspace}}/${{env.deploymentfileFolder}}/frontend.yml
            ${{github.workspace}}/${{env.deploymentfileFolder}}/ordering.yml
            ${{github.workspace}}/${{env.deploymentfileFolder}}/catalog.yml
  

