name: "chapter 09: create-container-and-push-frontend"
permissions:
  actions: write
  packages: write
  contents: read

on:
  push:
    branches: ["main"]
    paths:
    - 'frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: call reusable workflow to build and push container images  
      uses: ./.github/workflows/create-container-and-push.yml
      with:
        imageRepository: 'frontend'
        containerRegistry: 'ghcr.io/vriesmarcel'
        dockerfilePath: 'frontend/Dockerfile'
        deploymentFile: 'frontend.yaml'
        namespace: 'globoticket'