name: "chapter 09: deploy-frontend-container"
permissions:
  actions: write
  packages: write
  contents: read

env:
  imageRepository: 'frontend'
  containerRegistry: 'ghcr.io/vriesmarcel'
  dockerfilePath: 'frontend/Dockerfile'
  deploymentFile: 'frontend.yaml'
  namespace: 'globoticket'
  GITHUB_CONTEXT: ${{ toJSON(github) }}
  
on:
  release: 
     types: [published] 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: data from push to registry
        run: echo "$GITHUB_CONTEXT"
      - name: get release artifacts for deployment, picks data from latest release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: ${{ github.event.release.id }}
          regex: true
          file: ".*"
          target: './'

      - name: set kubernetes context
        uses: azure/k8s-set-context@v1
        id: setcontext
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBECONFIG}} 
      - name: provide pull secrets so we can pull the image from gitHub
        uses: azure/k8s-create-secret@v4
        with:
            namespace: '${{env.namespace}}'
            secret-name: 'pullsecret'
            container-registry-url: 'ghcr.io'
            container-registry-username: ${{ github.actor }}
            container-registry-password: ${{ secrets.EXTENDED_ACCESSTOKEN }}

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v4
        with:
          namespace: '${{env.namespace}}'
          manifests: |
             ./${{env.deploymentFile}}
