name: create-containers
env:
  imageRepository: 'frontend'
  containerRegistry: 'ghcr.io/vriesmarcel'
  dockerfilePath: 'frontend/Dockerfile'
  deploymentFile: 'frontend.yaml'
  namespace: 'globoticket'
on:
  workflow_dispatch:

jobs:
  build:
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build an image from Dockerfile
      run: |
        docker build -t ${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}} -f ${{env.dockerfilePath}} ${{github.workspace}}
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}}'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: push image to the registry
      run: |
        docker push ${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}}
