name: "test"
permissions:
  actions: write
  packages: write
  contents: read
on:
  workflow_dispatch:

env:
  deploymentfileFolder: 'deployment-automation'
  GH_TOKEN: ${{ github.token }} #required for gh tool

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Retrieve latest packages
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /user/packages/container/frontend/versions
