name: "test"
permissions:
  actions: write
  packages: write
  contents: read
on:
  workflow_dispatch:

env:
  deploymentfileFolder: 'deployment-automation'
  GH_TOKEN: ${{ github.token }} #required for gh tool

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Retrieve latest packages
        run: |
          export FRONTED_VERSION=$(gh api  /user/packages/container/frontend/versions | jq '.[0].metadata.container.tags[0]')
          echo "FRONTED_VERSION=$FRONTED_VERSION" >> $GITHUB_ENV
      - name: dump env
        run: |
          echo $FRONTED_VERSION